"""This file mirrors all the definitions made in the `py-dexter` Rust API.

Each class representing a dexter-equilibrium trait also provides all possible getters of all
implementors. The higher level wrappers are responsible for re-exporting the correct ones. An
`InvalidVariant` Exception is raised when python accesses a field that the wrapped type does not
have. It should not be visible to the user unless the call `._r` explicitly.
"""

from dexter.types import (
    Array1,
    FluxCoordinate,
    FluxCoordinateState,
    Interpolation1dType,
    ObjectType,
)

class _PyLastClosedFluxSurface:

    value: float
    kind: FluxCoordinate

    @classmethod
    def toroidal(cls, value: float) -> _PyLastClosedFluxSurface: ...
    @classmethod
    def poloidal(cls, value: float) -> _PyLastClosedFluxSurface: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class _PyQfactor:  # Trait and all possible getters
    object_type: ObjectType
    psi_state: FluxCoordinateState
    psip_state: FluxCoordinateState
    psi_last: float
    psip_last: float
    qlast: float
    qaxis: float
    path: str
    netcdf_version: str
    interp_type: Interpolation1dType

    @classmethod
    def build_unity(cls, lcfs: _PyLastClosedFluxSurface) -> _PyQfactor: ...
    @classmethod
    def build_parabolic(
        cls, qaxis: float, qlast: float, lcfs: _PyLastClosedFluxSurface
    ) -> _PyQfactor: ...
    @classmethod
    def build_nc(cls, path: str, interp_type: Interpolation1dType) -> _PyQfactor: ...
    def psip_of_psi(self, psi) -> float: ...
    def psi_of_psip(self, psip) -> float: ...
    def q_of_psi(self, psi) -> float: ...
    def q_of_psip(self, psip) -> float: ...
    def dpsip_dpsi(self, psi) -> float: ...
    def dpsi_dpsip(self, psip) -> float: ...
    def psi_of_q(self, psi) -> float: ...
    def psip_of_q(self, psip) -> float: ...
    def iota_of_psi(self, psi) -> float: ...
    def iota_of_psip(self, psip) -> float: ...
    def get_array(self, name: str) -> Array1: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class _PyCurrent:  # Trait and all possible getters
    object_type: ObjectType
    psi_state: FluxCoordinateState
    psip_state: FluxCoordinateState
    psi_last: float
    psip_last: float
    path: str
    netcdf_version: str
    interp_type: Interpolation1dType

    @classmethod
    def build_lar(cls) -> _PyCurrent: ...
    @classmethod
    def build_nc(cls, path: str, interp_type: Interpolation1dType) -> _PyCurrent: ...
    def g_of_psi(self, psi: float) -> float: ...
    def g_of_psip(self, psip: float) -> float: ...
    def i_of_psi(self, psi: float) -> float: ...
    def i_of_psip(self, psip: float) -> float: ...
    def dg_dpsi(self, psi: float) -> float: ...
    def dg_dpsip(self, psip: float) -> float: ...
    def di_dpsi(self, psi: float) -> float: ...
    def di_dpsip(self, psip: float) -> float: ...
    def get_array(self, name: str) -> Array1: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
