"""This file mirrors all the definitions made in the `py-dexter` Rust API.

Each class representing a dexter-equilibrium trait also provides all possible getters of all
implementors. The higher level wrappers are responsible for re-exporting the correct ones. An
`InvalidVariant` Exception is raised when python accesses a field that the wrapped type does not
have. It should not be visible to the user unless the call `._r` explicitly.
"""

from dexter.types import (
    Array1,
    Array2,
    ArrayShape,
    FluxCoordinate,
    FluxCoordinateState,
    Interpolation1dType,
    Interpolation2dType,
    PhaseMethod,
    ObjectType,
)

class _PyLastClosedFluxSurface:

    value: float
    kind: FluxCoordinate

    @classmethod
    def toroidal(cls, value: float) -> _PyLastClosedFluxSurface: ...
    @classmethod
    def poloidal(cls, value: float) -> _PyLastClosedFluxSurface: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class _PyGeometry:  # Trait and all possible getters
    object_type: ObjectType
    psi_state: FluxCoordinateState
    psip_state: FluxCoordinateState
    baxis: float
    raxis: float
    zaxis: float
    rgeo: float
    rlast: float
    psi_last: float
    psip_last: float
    path: str
    netcdf_version: str
    interp1d_type: Interpolation1dType
    interp2d_type: Interpolation2dType
    rlab_last: Array1
    zlab_last: Array1
    shape: ArrayShape

    @classmethod
    def build_lar(cls, baxis: float, raxis: float, rlast: float) -> _PyGeometry: ...
    @classmethod
    def build_nc(
        cls,
        path: str,
        interp1d_type: Interpolation1dType,
        interp2d_type: Interpolation2dType,
    ) -> _PyGeometry: ...
    def psip_of_psi(self, psi: float) -> float: ...
    def psi_of_psip(self, psip: float) -> float: ...
    def r_of_psi(self, psi: float) -> float: ...
    def r_of_psip(self, psip: float) -> float: ...
    def psi_of_r(self, r: float) -> float: ...
    def psip_of_r(self, r: float) -> float: ...
    def rlab_of_psi(self, psi: float, theta: float) -> float: ...
    def rlab_of_psip(self, psip: float, theta: float) -> float: ...
    def zlab_of_psi(self, psi: float, theta: float) -> float: ...
    def zlab_of_psip(self, psip: float, theta: float) -> float: ...
    def jacobian_of_psi(self, psi: float, theta: float) -> float: ...
    def jacobian_of_psip(self, psip: float, theta: float) -> float: ...
    def get_array(self, name: str) -> Array1: ...
    def get_array2d(self, name: str) -> Array2: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class _PyQfactor:  # Trait and all possible getters
    object_type: ObjectType
    psi_state: FluxCoordinateState
    psip_state: FluxCoordinateState
    psi_last: float
    psip_last: float
    qlast: float
    qaxis: float
    path: str
    netcdf_version: str
    interp_type: Interpolation1dType

    @classmethod
    def build_unity(cls, lcfs: _PyLastClosedFluxSurface) -> _PyQfactor: ...
    @classmethod
    def build_parabolic(
        cls, qaxis: float, qlast: float, lcfs: _PyLastClosedFluxSurface
    ) -> _PyQfactor: ...
    @classmethod
    def build_nc(cls, path: str, interp_type: Interpolation1dType) -> _PyQfactor: ...
    def psip_of_psi(self, psi: float) -> float: ...
    def psi_of_psip(self, psip: float) -> float: ...
    def q_of_psi(self, psi: float) -> float: ...
    def q_of_psip(self, psip: float) -> float: ...
    def dpsip_dpsi(self, psi: float) -> float: ...
    def dpsi_dpsip(self, psip: float) -> float: ...
    def psi_of_q(self, q: float) -> float: ...
    def psip_of_q(self, q: float) -> float: ...
    def iota_of_psi(self, psi: float) -> float: ...
    def iota_of_psip(self, psip: float) -> float: ...
    def get_array(self, name: str) -> Array1: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class _PyCurrent:  # Trait and all possible getters
    object_type: ObjectType
    psi_state: FluxCoordinateState
    psip_state: FluxCoordinateState
    psi_last: float
    psip_last: float
    path: str
    netcdf_version: str
    interp_type: Interpolation1dType

    @classmethod
    def build_lar(cls) -> _PyCurrent: ...
    @classmethod
    def build_nc(cls, path: str, interp_type: Interpolation1dType) -> _PyCurrent: ...
    def g_of_psi(self, psi: float) -> float: ...
    def g_of_psip(self, psip: float) -> float: ...
    def i_of_psi(self, psi: float) -> float: ...
    def i_of_psip(self, psip: float) -> float: ...
    def dg_dpsi(self, psi: float) -> float: ...
    def dg_dpsip(self, psip: float) -> float: ...
    def di_dpsi(self, psi: float) -> float: ...
    def di_dpsip(self, psip: float) -> float: ...
    def get_array(self, name: str) -> Array1: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class _PyBfield:  # Trait and all possible getters
    object_type: ObjectType
    psi_state: FluxCoordinateState
    psip_state: FluxCoordinateState
    path: str
    netcdf_version: str
    interp_type: Interpolation2dType
    baxis: float
    padding: int
    psi_last: float
    psip_last: float
    shape: ArrayShape
    shape_padded: ArrayShape

    @classmethod
    def build_lar(cls) -> _PyBfield: ...
    @classmethod
    def build_nc(
        cls,
        path: str,
        interp_type: Interpolation2dType,
        padding: int,
    ) -> _PyBfield: ...
    def b_of_psi(self, psi: float, theta: float) -> float: ...
    def b_of_psip(self, psip: float, theta: float) -> float: ...
    def db_dpsi(self, psi: float, theta: float) -> float: ...
    def db_dpsip(self, psip: float, theta: float) -> float: ...
    def db_of_psi_dtheta(self, psi: float, theta: float) -> float: ...
    def db_of_psip_dtheta(self, psip: float, theta: float) -> float: ...
    def get_array(self, name: str) -> Array1: ...
    def get_array2d(self, name: str) -> Array2: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class _PyMode:  # Trait and all possible getters
    object_type: ObjectType
    psi_state: FluxCoordinateState
    psip_state: FluxCoordinateState
    psi_last: float
    psip_last: float
    m: int
    n: int
    lcfs: _PyLastClosedFluxSurface
    epsilon: float
    phase: float
    path: str
    netcdf_version: str
    interp_type: Interpolation1dType
    phase_method: PhaseMethod
    analytical_threshold_index: int
    phase_average: float

    @classmethod
    def build_flute(
        cls,
        epsilon: float,
        lcfs: _PyLastClosedFluxSurface,
        m: int,
        n: int,
        phase: float,
    ) -> _PyMode: ...
    @classmethod
    def build_nc(
        cls,
        path: str,
        interp_type: Interpolation1dType,
        m: int,
        n: int,
        phase_method: PhaseMethod,
        analytical_threshold_index: int,
    ) -> _PyMode: ...
    # fmt: off
    def ampl_of_psi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def ampl_of_psip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def phase_of_psi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def phase_of_psip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def m_of_psi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def m_of_psip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dm_dpsi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dm_dpsip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dm_of_psi_dtheta(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dm_of_psip_dtheta(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dm_of_psi_dzeta(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dm_of_psip_dzeta(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dm_of_psi_dt(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dm_of_psip_dt(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    # fmt: on
    def get_array(self, name: str) -> Array1: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class _PyPerturbation:
    def __init__(self, modes: list[_PyMode]) -> None: ...
    # fmt: off
    def p_of_psi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def p_of_psip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_dpsi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_dpsip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psi_dtheta(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psip_dtheta(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psi_dzeta(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psip_dzeta(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psi_dt(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psip_dt(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    # fmt: on
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
