# The maximum amount of steps a particle can make before terminating its integration.
max_steps = 10_000_000
# The initial time step for the RKF45 adaptive step method. Should be small
# enough to account for fast particles. The value is empirical.
rkf45_first_step = 1e-3
# The relative tolerance of the energy error in every step.
energy_rel_tol = 1e-10
# The relative tolerance of the stepping error in every step.
step_rel_tol = 1e-9
# The starting capacity of the Evolution time series vectors.
evolution_init_capacity = 2000
