[project]
name = "dexter"
version = "0.2.0-pre.6"
description = "Calculations and simulations in analytical and reconstructed equilibria of toroidal fusion devices."
readme = "README.md"
authors = [
    { name = "George-Tsiamasiotis", email = "gt.develop@protonmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alpha-shapes>=1.1.1",
    "matplotlib>=3.11.1",
    "maturin>=1.14.1",
    "numpy==2.5.1", # maturin MSRV
    "pint>=0.25.3",
    "semver>=3.0.4",
]

[tool.maturin]
module-name = "dexter._core"
python-packages = ["dexter"]
python-source = "./py-dexter/"
manifest-path="./py-dexter/Cargo.toml"
# This also seems to solver maturin's and rust-analyzer's cache invalidation
# problem which forces pyo3 and rust-numpy to recompile every time
profile = "release"
editable-profile = "release"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "ipython>=9.16.0",
    "maturin-import-hook>=0.3.0",
    "patchelf>=0.17.2.4",
    "xarray>=2026.7.0",
    "netcdf4>=1.7.4",
]
plot = [
    "pygobject>=3.56.3",
]
test = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]
docs = [
    "mkdocstrings-python>=2.0.5",
    "zensical==0.0.53",
]

[tool.pytest.ini_options]
testpaths = [ # Run from workspace root
    "./py-dexter/pytests",
    "./py-dexter/dexter/equilibrium/*",
]
addopts = """
    --durations 2
    --doctest-glob='*.md'
    --doctest-glob='*.pyi'
    --doctest-glob='*.py'
    --doctest-modules
    --cov=dexter --cov-report term --cov-report html
"""
filterwarnings = [
    "ignore:.*Figure.*", # matplotlib non-interactive
]
