[test]
name = "poincare-maps"
manifest-path = "./Cargo.toml"
force-clean = false
skip-clean = true
output-dir = "./htmlcov/"
no-fail-fast = true
fail-immediately = true
color = "Always"
engine = "Llvm" # needed for pyo3
