[package]
name = "dexter-simulate"
version = "0.1.6-pre.2"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
rust-version.workspace = true
documentation.workspace = true
description = "Simulations of charge particles inside a plasma"

[dependencies]
dexter-common.workspace = true
dexter-machine.workspace = true
thiserror.workspace = true
ndarray.workspace = true
approx.workspace = true
parabola.workspace = true
rsl-interpolation.workspace = true
rayon = "1.12.0"
indicatif = "0.18.6"

[lints]
workspace = true

[[bin]]
name = "analytical_integration"
path = "bin/analytical_integration.rs"

[[bin]]
name = "numerical_integration"
path = "bin/numerical_integration.rs"
