[project]
name = "plots"
version = "0.1.0"
description = "Plots for poincare maps"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pygobject>=3.54.3"
]

[tool.setuptools]
py-modules = []
